name: Test Docker Build

on:
  workflow_dispatch:  # Manual trigger for testing

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: devops-todo

jobs:
  test-build:
    name: Test Docker Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Docker build locally (no push)
        run: |
          echo "Testing Docker build without pushing..."
          docker build -t test-devops-todo:latest .
          echo "✅ Docker build successful!"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Test AWS connection
        run: |
          echo "Testing AWS connection..."
          aws sts get-caller-identity
          echo "✅ AWS connection successful!"

      - name: Test ECR repository creation
        run: |
          echo "Testing ECR repository creation..."
          if aws ecr describe-repositories --repository-names ${{ env.ECR_REPOSITORY }} --region ${{ env.AWS_REGION }} > /dev/null 2>&1; then
            echo "✅ ECR repository already exists"
          else
            echo "Creating ECR repository..."
            aws ecr create-repository --repository-name ${{ env.ECR_REPOSITORY }} --region ${{ env.AWS_REGION }}
            echo "✅ ECR repository created"
          fi

      - name: Test ECR login
        run: |
          echo "Testing ECR login..."
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin $(aws sts get-caller-identity --query Account --output text).dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
          echo "✅ ECR login successful!"

      - name: Summary
        run: |
          echo "🎉 All tests passed!"
          echo "✅ Docker build works"
          echo "✅ AWS credentials work"
          echo "✅ ECR repository ready"
          echo "✅ ECR login works"